import co.sirdab.driver.buildsrc.BuildConfig
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("com.android.kotlin.multiplatform.library")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
}

kotlin {
    android {
        namespace = "${BuildConfig.BASE_NAMESPACE}.app"
        compileSdk = BuildConfig.COMPILE_SDK
        minSdk = BuildConfig.MIN_SDK

        compilerOptions {
            jvmTarget.set(JvmTarget.fromTarget(BuildConfig.JVM_TARGET))
        }

        androidResources {
            enable = true
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
            export(projects.shared)
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodel.compose)
        }

        commonMain.dependencies {
            api(projects.shared)

            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.material.icons.extended)
            implementation(libs.compose.ui)
            implementation(libs.compose.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodel.compose)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(libs.bundles.navigation3)

            implementation(libs.coil.compose)

            implementation(libs.bundles.koin.common)
        }

        iosMain.dependencies {
            implementation(libs.koin.core)
        }
    }
}

// iOS has no generated BuildConfig, so the same `driver.*` properties the Android app reads are
// written into a Kotlin object here. One source for both platforms, and `-P` overrides reach iOS
// too: Xcode builds the framework through Gradle.
val generateIosBackendConfig by tasks.registering {
    val apiBaseUrl = providers.gradleProperty("driver.apiBaseUrl")
    val supabaseUrl = providers.gradleProperty("driver.supabaseUrl")
    val supabaseAnonKey = providers.gradleProperty("driver.supabaseAnonKey")
    inputs.property("apiBaseUrl", apiBaseUrl)
    inputs.property("supabaseUrl", supabaseUrl)
    inputs.property("supabaseAnonKey", supabaseAnonKey)
    val outputDir = layout.buildDirectory.dir("generated/backendConfig/iosMain/kotlin")
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("co/sirdab/driver/di/IosBackendConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by :composeApp:generateIosBackendConfig from gradle.properties. Do not edit.
            |package co.sirdab.driver.di
            |
            |internal object IosBackendConfig {
            |    const val API_BASE_URL = "${apiBaseUrl.get()}"
            |    const val SUPABASE_URL = "${supabaseUrl.get()}"
            |    const val SUPABASE_ANON_KEY = "${supabaseAnonKey.get()}"
            |}
            |""".trimMargin(),
        )
    }
}

kotlin.sourceSets.named("iosMain") {
    kotlin.srcDir(generateIosBackendConfig)
}
